# Generated by Django 5.0.4 on 2024-04-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
    ]
